{% set name = "sktime" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alan-turing-institute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1c5ef3176ff845af2d0e3ec108a28cae3761d7df840df8ee290b602f2d994178

build:
  number: 0
  skip: true  # [(py==37 and aarch64) or py>39]

outputs:
  - name: sktime
    script: build_script.sh
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - llvm-openmp  # [osx]
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - deprecated >=1.2.13
        - {{ pin_compatible('numpy') }}
        - pandas >=1.1.0,<1.5.0
        - numba >=0.53
        - scikit-learn >=0.24.0,<1.2.0
        - statsmodels >=0.12.1
        - scipy <1.9.0
      run_constrained:
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - tsfresh >=0.17.0
        - stumpy >=1.5.1
        - tbats >=1.1.0
        - prophet >=1.1  # [not aarch64]
        - filterpy >=1.4.5
        - pykalman >=0.9.5
    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    requirements:
      run:
        - python
        - {{ pin_subpackage("sktime", max_pin="x.x.x.x") }}
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1  # [not win and py<=38]
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - tsfresh >=0.17.0
        - numba >=0.53
        # - catch22 >=0.1.0
        - stumpy >=1.5.1
        - tbats >=1.1.0
        - prophet >=1.1  # [not aarch64 and not linux and py>37]
        - filterpy >=1.4.5
        - pykalman >=0.9.5
        - gluonts >=0.9.0
        - kotsu >=0.3.1
        - tensorflow
        - tensorflow-probability
        - tslearn >=0.5.2
        - statsforecast >=0.5.2
        - dtw-python
        - esig ==0.9.7
        - mne
        - pyod >=0.8.0

    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/alan-turing-institute/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  doc_url: https://www.sktime.org/en/latest/
  dev_url: https://github.com/alan-turing-institute/sktime

extra:
  recipe-maintainers:
    - fkiraly
    - dhirschfeld
    - freddyaboulton
    - lmmentel
    - mloning
