name: sktime-all-extra
dependencies:
  - python
  - matplotlib-base >=3.3.2
  - pmdarima >=1.8.0,!=1.8.1
  - scikit-posthocs >=0.6.5
  - seaborn >=0.11.0
  - tsfresh >=0.17.0
  - numba >=0.53
  - stumpy >=1.5.1
  - tbats >=1.1.0
  - prophet >=1.1  # [not aarch64 and not linux and py>37]
  - filterpy >=1.4.5
  - pykalman >=0.9.5
  - tensorflow
  - tensorflow-probability
  - tslearn >=0.5.2
  - statsforecast >=0.5.2
  - dtw-python
  - mne
  - pyod >=0.8.0
  - pip
  - pip:
    - esig ==0.9.7
    - gluonts >=0.9.0
    - kotsu >=0.3.1